source 'https://rubygems.org'

# xcodeproj 1.x excludes CFPropertyList 4.x, while 3.0.9 only supports Ruby < 3.2.
gem 'CFPropertyList', '3.0.8'
gem 'cocoapods', '1.14.3'
gem 'cocoapods-lynx-library', '4.3.0.pre.nightly.202609090610.180.g5e30c9e6'
