platform :ios, '12.0'
source 'https://github.com/lynx-family/Specs.git'
source 'https://cdn.cocoapods.org/'
install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

plugin 'cocoapods-lynx-library'

target 'NeedleHost' do
  use_frameworks! :linkage => :static

  use_lynx_library!(
    :root => __dir__,
    :output_dir => File.join(__dir__, 'generated/lynx-library')
  )

  lynx_version = '4.3.0-nightly.202609090610.180.g5e30c9e6'
  pod 'Lynx', lynx_version
  pod 'LynxBase', lynx_version
  pod 'LynxServiceAPI', lynx_version
end
